CREATE TABLE IF NOT EXISTS users (
  id         SERIAL PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  password   VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id          SERIAL PRIMARY KEY,
  title       VARCHAR(255) NOT NULL,
  completed   BOOLEAN DEFAULT false,
  tag         VARCHAR(50) DEFAULT 'DEFAULT',
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  description TEXT DEFAULT ''
);
